name: PortFolio CI

on:
    push:
        branches: ["_dev", "raju"]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                node-version: [18.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
              with:
                  version: 6.10.0
            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
            - name: Installing dependencies...
              run: pnpm install
            - name: starting project test...
              run: pnpm test --if-present
            - name: test variable
              run: echo ${{vars.MONGODB_URI}}
            - name: building production build...
              run: pnpm run build --if-present
              env:
                  MONGODB_URI: ${{vars.MONGODB_URI}}
